more cleanly format Error's
Summary:
Previously we used to output errors like this: `SyntaxError "invalid syntax"`

Now ERRPY will output: `SyntaxError invalid syntax` . i.e. we remove the `"`'s.

Removing the `"` makes it easier to define unit tests in OCaml code (no need to use a \ all over the output strings for comparison) and brings the output in line with the output from CPython:
```
[jat@devvm5624.lla0 /data/users/jat/fbsource/fbcode/tools/pyre/source (ada41d722)]$ python3
Python 3.8.6 (default, Oct 24 2022, 10:31:55)
[GCC 11.x 20220830 (Facebook) 11.2.1+] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> %wfdsdf
  File "<stdin>", line 1
    %wfdsdf
    ^
SyntaxError: invalid syntax
```

Also took the oppertunity to refactor the logic for this into its own function: `recoverable_error_to_string`

Reviewed By: stroxler

Differential Revision:
D43976975

Privacy Context Container: L1152058

fbshipit-source-id: db73390f74028539fb6c19a850c8afbae31cfaef